export const GET_TRACKS = "GET_TRACKS";
export const GET_TRACKS_SUCCESS = "GET_TRACKS_SUCCESS";
export const ADD_TRACK = 'ADD_TRACK';
export const ADD_TRACK_PROCESS = 'ADD_TRACK_PROCESS';
export const ADD_TRACK_SUCCESS = 'ADD_TRACK_SUCCESS';
export const INIT_EDIT_FORM = 'INIT_EDIT_FORM;'